HalloDoc/HalloDocWeb/Controllers/RequestPagesController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using BusinessLogic.Interface;
using DataAccess.DataContext;
using DataAccess.DataModels;
using DataAccess.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HalloDocWeb.Controllers
{
    public class RequestPagesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly INotyfService _notyf;
        private readonly IPatientService _patientService;


        public RequestPagesController(ApplicationDbContext context, IPatientService patientService,INotyfService notyf)
        {
            _notyf = notyf;
            _context = context;
            _patientService = patientService;
        }
        public IActionResult PatientSubmitRequest()
        {
            return View();
        }
        //GET
        public IActionResult PatientRequest()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PatientRequest(PatientSubmitRequest userDetails)
        {
            if (ModelState.IsValid)
            {
                _patientService.PatientRequest(userDetails);
                _notyf.Success("Request Submitted Successfully", 3);
                return RedirectToAction("Index", "Home");
            }
            return View(userDetails);
        }

        [HttpPost]
        public JsonResult PatientCheckEmail(string email)
        {
            bool emailExists = _context.Users.Any(u => u.Email == email);
            return Json(new { exists = emailExists });
        }

        //GET
        public IActionResult FamilyFriendRequest()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult FamilyFriendRequest(FamilyFriendSubmitRequest userDetails)
        {
            if (ModelState.IsValid)
            {
                _patientService.FamilyFriendRequest(userDetails);
                _notyf.Success("Request Submitted Successfully", 3);
                return RedirectToAction("Index", "Home");

            }
            return View(userDetails);
        }


        //GET
        public IActionResult ConciergeRequest()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ConciergeRequest(ConciergeSubmitRequest userDetails)
        {
            if (ModelState.IsValid)
            {
                _patientService.ConciergeRequest(userDetails);
                _notyf.Success("Request Submitted Successfully", 3);
                return RedirectToAction("Index", "Home");

            }
            return RedirectToAction("Index", "Home");
        }


        //Business Request
        public IActionResult BusinessRequest()
        {
            return View();
        }


        [HttpPost]
        public IActionResult BusinessRequest(BusinessSubmitRequest userDetails)
        {
            if (ModelState.IsValid)
            {
                _patientService.BusinessRequest(userDetails);
                _notyf.Success("Request Submitted Successfully", 3);
                return RedirectToAction("Index", "Home");
            }
            return View(userDetails);

        }
        public Task<bool> IsEmailExists(string email)
        {
            bool isExist = _context.Aspnetusers.Any(x => x.Email == email);
            if (isExist)
            {
                return Task.FromResult(true);
            }
            return Task.FromResult(false);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HalloDoc/HalloDocWeb/Views/RequestPages/BusinessRequest.cshtml
@model BusinessSubmitRequest
@{
    ViewData["Title"] = "BusinessRequest";
}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/intl-tel-input@19.2.16/build/css/intlTelInput.css">
<script src="https://cdn.jsdelivr.net/npm/intl-tel-input@19.2.16/build/js/intlTelInput.min.js"></script>


@await Html.PartialAsync("warningModal")

@await Html.PartialAsync("header")
<div class="mt-3">
    <a asp-controller="RequestPages" asp-action="PatientSubmitRequest" class="btn btn-outline-info float-end">
        <span class="h6 p-0 m-0 text-center" style="color: #10bce9;">&#60; Back</span>
    </a>
</div>
<div class="container">

    <form method="post" enctype="multipart/form-data">
        <!-- patient Information -->
        <div class=" row form-group">
            <h2>Business/Partner Information</h2>

            <!-- firstname -->

            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">

                <input asp-for="FirstName" type="text" class="form-control" id="exampleFormControlInput1">
                <label for="exampleFormControlInput1">Your Firstname</label>

            </div>
            <!-- Lastname -->
            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="LastName" type="text" class="form-control" id="exampleFormControlInput1">
                <label for="exampleFormControlInput1">Your Lastname</label>
            </div>

            <!-- Phone Number -->
            <div class="col-lg-6 col-md-12 col-sm-12 col-12 form-group mt-3 form-floating">

                <input asp-for="Phone" type="tel" class="form-control phone" id="business-phone" placeholder="(555) 555-5555">
            </div>

            <!-- Email -->
            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">

                <input asp-for="Email" type="email" class="form-control" id="floatingInput">
                <label for="floatingInput">Email</label>

            </div>

            <!-- Relation with patient -->

            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="BusinessName" type="text" class="form-control" id="exampleFormControlInput1">
                <label for="exampleFormControlInput1">Business/Property Name</label>
            </div>
            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="CaseNumber" type="text" class="form-control" id="exampleFormControlInput1">
                <label for="exampleFormControlInput1">Case Number <i>(optional)</i></label>
            </div>

            <div class="row mt-3">


                <h2>Patient Information</h2>

                <!-- symptoms -->

                <div class="col-lg-12 col-md-12 col sm-12 col-12 ">
                    <textarea asp-for="Symptoms" class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Enter brief details of symptoms (optional)"></textarea>
                </div>

                <!-- firstname -->

                <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">

                    <input asp-for="PatientFirstName" type="text" class="form-control" id="exampleFormControlInput1">
                    <label for="exampleFormControlInput1">Patient's' Firstname</label>

                </div>
                <!-- Lastname -->
                <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                    <input asp-for="PatientLastName" type="text" class="form-control" id="exampleFormControlInput1">
                    <label for="exampleFormControlInput1">Patient's Lastname</label>
                </div>

                <!-- Date of birth -->

                <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3">
                    <input asp-for="PatientDateOfBirth" type="date" class="form-control" id="exampleFormControlInput1">
                </div>


                <!-- Patient Contact Info -->
                <div class="row mt-3">
                    <h2>Patient Contact Information</h2>
                </div>
                <!-- Email -->
                <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">

                    <input asp-for="PatientEmail" type="email" class="form-control" id="floatingInputemail">
                    <label for="floatingInputemail">Email</label>

                </div>
                <!-- Phone Number -->
                <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                    <input asp-for="PatientPhone" type="tel" class="form-control" id="floatingInput">
                    <label for="floatingInput">Number</label>
                </div>

                <div class="row" id="hiddendiv" style="display:none">

                    <div class="col-md-6 col-12">
                        <div class="form-floating mt-3">
                            <input asp-for="Password" type="password" class="form-control" placeholder="Leave a comment here"
                                   id="floatingTextarea2" />
                            <label for="floatingTextarea2">Password</label>
                        </div>
                    </div>

                    <div class="col-md-6 col-12">
                        <div class="form-floating mt-3">
                            <input asp-for="ConfirmPassword" type="password" class="form-control" placeholder="Leave a comment here"
                                   id="floatingTextarea2" />
                            <label for="floatingTextarea2">Confirm Password</label>
                            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                        </div>
                    </div>

                </div>


                <!-- Patient Location -->

                <div class="row mt-3">
                    <h2>Patient Location</h2>
                </div>
                <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                    <input asp-for="Street" type="text" class="form-control" id="floatingInput">
                    <label for="floatingInput">Street</label>
                </div>
                <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                    <input asp-for="City" type="text" class="form-control" id="floatingInput">
                    <label for="floatingInput">City</label>
                </div>
                <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                    <input asp-for="State" type="text" class="form-control" id="floatingInput">
                    <label for="floatingInput">State</label>
                </div>
                <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                    <input asp-for="ZipCode" type="number" class="form-control" id="floatingInput">
                    <label for="floatingInput">Zip Code</label>
                </div>
                <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                    <input asp-for="PatientRoom" type="text" class="form-control" id="floatingInput">
                    <label for="floatingInput">Room #/Suit (Optional)</label>
                </div>
                <div class="row mt-3">
                    <h2>(Optional) Upload Photo or Document</h2>
                </div>
                <div class="form mb-3 col-lg-12 col-md-12 col-sm-12 d-flex">

                    <input type="file" asp-for="File" class="form-control" placeholder="Select File">

                </div>


                <!-- Submit and Cancel button -->
                <div class="d-flex justify-content-end mt-3 gap-1">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                </div>
            </div>
        </div>
    </form>
</div>
<br />
@await Html.PartialAsync("footer")


<script>
    var phoneInputField = document.querySelector("#business-phone");
    var phoneInput = window.intlTelInput(phoneInputField, {
        utilsScript:
            "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/utils.js",
    });

    var phoneInputField = document.querySelector("#patient-phone");
    var phoneInput = window.intlTelInput(phoneInputField, {
        utilsScript:
            "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/utils.js",
    });
</script>

<script type="text/javascript">
    $(document).ready(function () {

        $('#floatingInputemail').on('blur', function () {
            var email = $(this).val();
            $.ajax({
                url: '/RequestPages/PatientCheckEmail',
                type: 'POST',
                data: { email: email },
                success: function (data) {
                    if (!data.exists) {
                        $('#hiddendiv').show();
                    }
                    else {
                        $('#hiddendiv').hide();
                    }
                }
            });
        });
    });
</script>

HalloDoc/HalloDocWeb/Views/RequestPages/ConciergeRequest.cshtml
@model ConciergeSubmitRequest
@{
    ViewData["Title"] = "ConciergeRequest";
}
@await Html.PartialAsync("warningModal")
@await Html.PartialAsync("header")
<div class="mt-3">
    <a asp-controller="RequestPages" asp-action="PatientSubmitRequest" class="btn btn-outline-info float-end">
        <span class="h6 p-0 m-0 text-center" style="color: #10bce9;">&#60; Back</span>
    </a>
</div>
<div class="container">

    <form method="post" enctype="multipart/form-data">
        <!-- patient Information -->
        <div class=" row form-group">
            <h2>Concierge Information</h2>

            <!-- firstname -->

            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">

                <input asp-for="FirstName" type="text" class="form-control" id="exampleFormControlInput1">
                <label for="exampleFormControlInput1">Your Firstname</label>

            </div>
            <!-- Lastname -->
            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="LastName" type="text" class="form-control" id="exampleFormControlInput1">
                <label for="exampleFormControlInput1">Your Lastname</label>
            </div>

            <!-- Phone Number -->
            <div class="col-lg-6 col-md-12 col-sm-12 col-12 form-group mt-3 form-floating">

                <input asp-for="Phone" type="tel" class="form-control phone" id="floatingInput" placeholder="(555) 555-5555">
            </div>

            <!-- Email -->
            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">

                <input asp-for="Email" type="email" class="form-control" id="floatingInput">
                <label for="floatingInput">Email</label>

            </div>

            <!-- Relation with patient -->

            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="PropertyName" type="text" class="form-control" id="exampleFormControlInput1">
                <label for="exampleFormControlInput1">Hotel/Property Name</label>

            </div>

            <div class="row mt-3">
                <h2>Concierge Location</h2>
            </div>
            <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="Street" type="text" class="form-control" id="floatingInput">
                <label for="floatingInput">Street</label>
            </div>
            <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="City" type="text" class="form-control" id="floatingInput">
                <label for="floatingInput">City</label>
            </div>
            <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="State" type="text" class="form-control" id="floatingInput">
                <label for="floatingInput">State</label>
            </div>
            <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="ZipCode" type="number" class="form-control" id="floatingInput">
                <label for="floatingInput">Zip Code</label>
            </div>

            <h2>Patient Information</h2>

            <!-- symptoms -->

            <div class="col-lg-12 col-md-12 col sm-12 col-12 ">
                <textarea asp-for="Symptoms" class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Enter brief details of symptoms (optional)"></textarea>
            </div>

            <!-- firstname -->

            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">

                <input asp-for="PatientFirstName" type="text" class="form-control" id="exampleFormControlInput1">
                <label for="exampleFormControlInput1">Patient Firstname</label>

            </div>
            <!-- Lastname -->
            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="PatientLastName" type="text" class="form-control" id="exampleFormControlInput1">
                <label for="exampleFormControlInput1">Patient Lastname</label>
            </div>

            <!-- Date of birth -->

            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3">
                <input asp-for="DateOfBirth" type="date" class="form-control" id="exampleFormControlInput1">
            </div>


            <!-- Patient Contact Info -->
            <div class="row mt-3">
                <h2>Patient Contact Information</h2>
            </div>
            <!-- Email -->
            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">

                <input asp-for="PatientEmail" type="email" class="form-control" id="floatingInputemail">
                <label for="floatingInputemail">Email</label>

            </div>
            <!-- Phone Number -->
            <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="PatientPhone" type="tel" class="form-control" id="floatingInput">
                <label for="floatingInput">Number</label>
            </div>

            <div class="row" id="hiddendiv" style="display:none">

                <div class="col-md-6 col-12">
                    <div class="form-floating mt-3">
                        <input asp-for="Password" type="password" class="form-control" placeholder="Leave a comment here"
                               id="floatingTextarea2" />
                        <label for="floatingTextarea2">Password</label>
                    </div>
                </div>

                <div class="col-md-6 col-12">
                    <div class="form-floating mt-3">
                        <input asp-for="ConfirmPassword" type="password" class="form-control" placeholder="Leave a comment here"
                               id="floatingTextarea2" />
                        <label for="floatingTextarea2">Confirm Password</label>
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                </div>

            </div>



            <!-- Patient Location -->

            <div class="row mt-3">
                <h2>Patient Location</h2>
            </div>
            <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="PatientStreet" type="text" class="form-control" id="floatingInput">
                <label for="floatingInput">Street</label>
            </div>
            <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="PatientCity" type="text" class="form-control" id="floatingInput">
                <label for="floatingInput">City</label>
            </div>
            <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="PatientState" type="text" class="form-control" id="floatingInput">
                <label for="floatingInput">State</label>
            </div>
            <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="PatientZipCode" type="number" class="form-control" id="floatingInput">
                <label for="floatingInput">Zip Code</label>
            </div>
            <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="PatientRoom" type="text" class="form-control" id="floatingInput">
                <label for="floatingInput">Room #/Suit (Optional)</label>
            </div>
            <div class="row mt-3">
                <h2>(Optional) Upload Photo or Document</h2>
            </div>
            <div class="form mb-3 col-lg-12 col-md-12 col-sm-12 d-flex">

                <input type="file" asp-for="File" class="form-control" placeholder="Select File">

            </div>

            <!-- Submit and Cancel button -->
            <div class="d-flex justify-content-end mt-3 gap-1">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="reset" class="btn btn-secondary">Cancel</button>
            </div>
        </div>

    </form>
</div>

<br />
@await Html.PartialAsync("footer")

<script type="text/javascript">
    $(document).ready(function () {

        $('#floatingInputemail').on('blur', function () {
            var email = $(this).val();
            $.ajax({
                url: '/RequestPages/PatientCheckEmail',
                type: 'POST',
                data: { email: email },
                success: function (data) {
                    if (!data.exists) {
                        $('#hiddendiv').show();
                    }
                    else {
                        $('#hiddendiv').hide();
                    }
                }
            });
        });
    });
</script>

HalloDoc/HalloDocWeb/Views/RequestPages/FamilyFriendRequest.cshtml
@model FamilyFriendSubmitRequest


@{
    ViewData["Title"] = "FamilyFriendRequest";
}
@await Html.PartialAsync("warningModal")
@await Html.PartialAsync("header")


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/intl-tel-input@19.2.16/build/css/intlTelInput.css">
<script src="https://cdn.jsdelivr.net/npm/intl-tel-input@19.2.16/build/js/intlTelInput.min.js"></script>


<div class="mt-3">
    <a asp-controller="RequestPages" asp-action="PatientSubmitRequest" class="btn btn-outline-info float-end">
        <span class="h6 p-0 m-0 text-center" style="color: #10bce9;">&#60; Back</span>
    </a>
</div>
<div class="container">

    <form method="post" enctype="multipart/form-data">
        <!-- family/friend Information -->
        <div class=" row form-group">
            <h2>Family/Friend Information</h2>

            <!-- firstname -->

            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">

                <input asp-for="FirstName" type="text" class="form-control" id="exampleFormControlInput1">
                <label for="exampleFormControlInput1">Your Firstname</label>
                <span class="text-danger" asp-validation-for="FirstName"></span>


            </div>
            <!-- Lastname -->
            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="LastName" type="text" class="form-control" id="exampleFormControlInput1">
                <label for="exampleFormControlInput1">Your Lastname</label>
            </div>

            <!-- Phone Number -->
            <div class="col-lg-6 col-md-12 col-sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="Phone" type="tel" class="form-control phone" id="floatingInput" placeholder="(555) 555-5555">
                <span class="text-danger" asp-validation-for="Phone"></span>
            </div>

            <!-- Email -->
            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">

                <input asp-for="Email" type="email" class="form-control" id="floatingInput">
                <label for="floatingInput">Email</label>
                <span class="text-danger" asp-validation-for="Email"></span>
            </div>

            <!-- Relation with patient -->

            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="RelationWithPatient" type="text" class="form-control" id="exampleFormControlInput1">
                <label for="exampleFormControlInput1">Relation with patient</label>
                <span class="text-danger" asp-validation-for="RelationWithPatient"></span>
            </div>

            <h2>Patient Information</h2>

            <!-- symptoms -->

            <div class="col-lg-12 col-md-12 col sm-12 col-12 ">
                <textarea asp-for="Symptoms" class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Enter brief details of symptoms (optional)"></textarea>
            </div>

            <!-- firstname -->

            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">

                <input asp-for="PatientFirstName" type="text" class="form-control" id="exampleFormControlInput1">
                <label for="exampleFormControlInput1">Patient's Firstname</label>
                <span class="text-danger" asp-validation-for="PatientFirstName"></span>


            </div>
            <!-- Lastname -->
            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="PatientLastName" type="text" class="form-control" id="exampleFormControlInput1">
                <label for="exampleFormControlInput1">Patient's Lastname</label>
            </div>

            <!-- Date of birth -->

            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3">
                <input asp-for="DateOfBirth" type="date" class="form-control" id="exampleFormControlInput1">
                <span class="text-danger" asp-validation-for="DateOfBirth"></span>

            </div>


            <!-- Patient Contact Info -->
            <div class="row mt-3">
                <h2>Patient Contact Information</h2>
            </div>
            <!-- Email -->
            <div class="col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">

                <input asp-for="PatientEmail" type="email" class="form-control" id="floatingInputemail">
                <label for="floatingInputemail">Patient's Email</label>
                <span class="text-danger" asp-validation-for="PatientEmail"></span>


            </div>
            <!-- Phone Number -->
            <div class="col-lg-6 col-md-12 col-sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="PatientPhone" type="tel" class="form-control phone" id="floatingInput" placeholder="(555) 555-5555">
                <span class="text-danger" asp-validation-for="PatientPhone"></span>

            </div>

            <div class="row" id="hiddendiv" style="display:none">

                <div class="col-md-6 col-12">
                    <div class="form-floating mt-3">
                        <input asp-for="Password" type="password" class="form-control" placeholder="Leave a comment here"
                               id="floatingTextarea2" />
                        <label for="floatingTextarea2">Password</label>
                    </div>
                </div>

                <div class="col-md-6 col-12">
                    <div class="form-floating mt-3">
                        <input asp-for="ConfirmPassword" type="password" class="form-control" placeholder="Leave a comment here"
                               id="floatingTextarea2" />
                        <label for="floatingTextarea2">Confirm Password</label>
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                </div>

            </div>



            <!-- Patient Location -->

            <div class="row mt-3">
                <h2>Patient Location</h2>
            </div>
            <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="Street" type="text" class="form-control" id="floatingInput">
                <label for="floatingInput">Street</label>
            </div>
            <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="City" type="text" class="form-control" id="floatingInput">
                <label for="floatingInput">City</label>
            </div>
            <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="State" type="text" class="form-control" id="floatingInput">
                <label for="floatingInput">State</label>
            </div>
            <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="ZipCode" type="number" class="form-control" id="floatingInput">
                <label for="floatingInput">Zip Code</label>
            </div>
            <div class=" col-lg-6 col-md-12 col sm-12 col-12 form-group mt-3 form-floating">
                <input asp-for="Room" type="text" class="form-control" id="floatingInput">
                <label for="floatingInput">Room #/Suit (Optional)</label>
            </div>
            <div class="row mt-3">
                <h2>(Optional) Upload Photo or Document</h2>
            </div>
            <div class="form mb-3 col-lg-12 col-md-12 col-sm-12 d-flex">
                <input type="file" asp-for="File" class="form-control" placeholder="Select File">
            </div>

            <!-- Submit and Cancel button -->
            <div class="d-flex justify-content-end mt-3 gap-1">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="reset" class="btn btn-secondary">Cancel</button>
            </div>
        </div>

    </form>

</div>
<br />
@await Html.PartialAsync("footer")

<script>
    const input = document.querySelector("input[type='tel']");
    window.intlTelInput(input, {
        utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@19.2.16/build/js/utils.js",
    })
</script>

<script>
    const input = document.querySelector("#patientPhone");
    window.intlTelInput(input, {
        utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@19.2.16/build/js/utils.js",
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {

        $('#floatingInputemail').on('blur', function () {
            var email = $(this).val();
            $.ajax({
                url: '/RequestPages/PatientCheckEmail',
                type: 'POST',
                data: { email: email },
                success: function (data) {
                    if (!data.exists) {
                        $('#hiddendiv').show();
                    }
                    else {
                        $('#hiddendiv').hide();
                    }
                }
            });
        });
    });
</script>