HalloDoc/HalloDocWeb/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using DataAccess.ViewModels;
using DataAccess.DataContext;
using BusinessLogic.Interface;
using BusinessLogic.Repository;
using DataAccess.DataModels;
using System.Text.Json.Nodes;
using AspNetCoreHero.ToastNotification.Abstractions;
using System.Text;
using OfficeOpenXml;
using System.Reflection;


namespace HalloDocWeb.Controllers
{
    [CustomAuthorize((int)AllowRole.Admin)]
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IAdminService _adminService;
        private readonly INotyfService _notyf;

        public AdminController(ApplicationDbContext context, IAdminService adminService, INotyfService notyf)
        {
            _notyf = notyf;
            _context = context;
            _adminService = adminService;
        }

        /////////////////////////////AdminDashboard//////////////////////////////////////

        public IActionResult AdminDashboard(int status)
        {
            var data = _adminService.AdminDashboard();
            int? adminId = HttpContext.Session.GetInt32("adminId");
            var dashData = new AdminDashboard
            {
                Status = status,
                CountRequestViewModel = data.CountRequestViewModel,
            };
            return View("Dashboard/AdminDashboard", dashData);
        }
        public IActionResult ViewCase(int reqClientId)
        {
            int? adminId = HttpContext.Session.GetInt32("adminId");

            var obj = _adminService.ViewCaseViewModel(reqClientId);

            return View("Pages/ViewCase", obj);
        }
        public IActionResult ViewNotes(int reqClientId)
        {
            _ = HttpContext.Session.GetInt32("adminId");
            var obj = _adminService.ViewNotes(reqClientId);
            return View("Pages/ViewNotes", obj);
        }
        [HttpPost]
        public IActionResult ViewNotes(ViewNotes viewNotes)
        {
            if (ModelState.IsValid)
            {
                int? adminId = HttpContext.Session.GetInt32("adminId");
                _adminService.ViewNotesUpdate(viewNotes);
                _notyf.Success("Note Updated Successfully", 3);
                return ViewNotes(viewNotes.Requestclientid);
            }
            return View("Pages/ViewNotes", viewNotes.Requestclientid);
        }
        [HttpPost]
        public IActionResult PartialTable(int status, SearchViewModel obj)
        {
            var data = _adminService.AdminDashboard();

            if (obj.Name != null || obj.Sorting != null)
            {
                var searchData = _adminService.SearchPatient(obj, data);
                if (status == 1)
                {
                    var parseData = searchData.NewReqViewModel;
                    return PartialView("PartialTable/_newRequestView", parseData);
                }
                else if (status == 2)
                {
                    var parseData = searchData.PendingReqViewModel;
                    return PartialView("PartialTable/_PendingRequestView", parseData);
                }
                else if (status == 8)
                {
                    var parseData = searchData.ActiveReqViewModels;
                    return PartialView("PartialTable/_activeRequestView", parseData);
                }
                else if (status == 4)
                {
                    var parseData = searchData.ConcludeReqViewModel;
                    return PartialView("PartialTable/_concludeReqView", parseData);
                }
                else if (status == 5)
                {
                    var parseData = searchData.CloseReqViewModels;
                    return PartialView("PartialTable/_closeReqView", parseData);
                }
                else
                {
                    var parseData = searchData.UnpaidReqViewModels;
                    return PartialView("PartialTable/_unpaidReqView", parseData);
                }
            }

            if (status == 1)
            {
                var parseData = data.NewReqViewModel;
                return PartialView("PartialTable/_newRequestView", parseData);
            }
            else if (status == 2)
            {
                var parseData = data.PendingReqViewModel;
                return PartialView("PartialTable/_PendingRequestView", parseData);
            }
            else if (status == 8)
            {
                var parseData = data.ActiveReqViewModels;
                return PartialView("PartialTable/_activeRequestView", parseData);
            }
            else if (status == 4)
            {
                var parseData = data.ConcludeReqViewModel;
                return PartialView("PartialTable/_concludeReqView", parseData);
            }
            else if (status == 5)
            {
                var parseData = data.CloseReqViewModels;
                return PartialView("PartialTable/_closeReqView", parseData);
            }
            else
            {
                var parseData = data.UnpaidReqViewModels;
                return PartialView("PartialTable/_unpaidReqView", parseData);
            }

        }

        [HttpPost]
        public IActionResult SearchedRegion(int status, int regionId)
        {
            if (regionId == 0)
            {
                return RedirectToAction("AdminDashboard");
            }
            var searchData = _adminService.SearchRegion(regionId);
            if (status == 1)
            {
                var parseData = searchData.NewReqViewModel;
                return PartialView("PartialTable/_newRequestView", parseData);
            }
            else if (status == 2)
            {
                var parseData = searchData.PendingReqViewModel;
                return PartialView("PartialTable/_PendingRequestView", parseData);
            }
            else if (status == 8)
            {
                var parseData = searchData.ActiveReqViewModels;
                return PartialView("PartialTable/_activeRequestView", parseData);
            }
            else if (status == 4)
            {
                var parseData = searchData.ConcludeReqViewModel;
                return PartialView("PartialTable/_concludeReqView", parseData);
            }
            else if (status == 5)
            {
                var parseData = searchData.CloseReqViewModels;
                return PartialView("PartialTable/_closeReqView", parseData);
            }
            else
            {
                var parseData = searchData.UnpaidReqViewModels;
                return PartialView("PartialTable/_unpaidReqView", parseData);
            }


        }

        [HttpPost]
        public IActionResult AdminDashboard(SearchViewModel obj)
        {
            //ViewBag.AdminName = HttpContext.Session.GetString("adminToken").ToString();
            ViewBag.AdminId = HttpContext.Session.GetInt32("adminId");
            var data = _adminService.AdminDashboard();

            var searchedData = _adminService.SearchPatient(obj, data);

            var dashData = new AdminDashboard
            {
                CountRequestViewModel = searchedData.CountRequestViewModel,
            };

            return View("Dashboard/AdminDashboard", dashData);

        }
        public IActionResult CancelCaseModal(int requestClientId)
        {
            CancelCase cancelCase = new()
            {
                ReqClientid = requestClientId,
                Casetags = _context.Casetags,
            };
            return PartialView("PopUpModals/_CancelCaseView", cancelCase);
        }
        public IActionResult AssignCaseModal(int requestClientId)
        {
            AssignCase assignCase = new()
            {
                ReqClientid = requestClientId,
                Region = _context.Regions,
                Physicians = _context.Physicians
            };
            return PartialView("PopUpModals/_AssignCaseView", assignCase);
        }
        public IActionResult TransferCaseModal(int requestClientId)
        {
            TransferCase transferCase = new()
            {
                ReqClientid = requestClientId,
                Region = _context.Regions,
                Physicians = _context.Physicians
            };
            return PartialView("PopUpModals/_TransferCaseView", transferCase);
        }
        public IActionResult SendAgreement(int requestClientId)
        {
            SendAgreementCase sendAgreement = new()
            {
                ReqClientid = requestClientId,
            };
            return PartialView("PopUpModals/_SendAgreementModal", sendAgreement);
        }
        public IActionResult BlockCaseModal(int requestClientId)
        {
            BlockCase blockCase = new()
            {
                ReqClientid = requestClientId,
            };
            return PartialView("PopUpModals/_BlockCaseView", blockCase);
        }
        [HttpPost]
        public IActionResult CancelCase(int ReqClientid, int CaseTagId, string AddOnNotes)
        {
            CancelCase cancelCase = new()
            {
                ReqClientid = ReqClientid,
                CaseTagId = CaseTagId,
                AddOnNotes = AddOnNotes,
            };
            if (ModelState.IsValid)
            {
                _adminService.CancelCase(cancelCase);
                _notyf.Success("Case has been successfully cancelled", 3);
                return RedirectToAction("AdminDashboard");
            }
            _notyf.Error("Please try again", 3);

            return PartialView("PopUpModals/_CancelCaseView", cancelCase);
        }
        [HttpPost]

HalloDoc/HalloDocWeb/Controllers/PatientController.cs
using DataAccess.DataModels;
using DataAccess.DataContext;
using Microsoft.AspNetCore.Mvc;
using BusinessLogic.Interface;
using DataAccess.ViewModels;
using System.Diagnostics;
using BusinessLogic.Repository;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;


namespace HalloDocWeb.Controllers
{
    [CustomAuthorize((int)AllowRole.Patient)]
    public class PatientController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IAuthService _authService;
        private readonly IPatientService _patientService;
        private readonly INotyfService _notyf;

        public PatientController(ApplicationDbContext context, IAuthService authService, IPatientService patientService, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
            _authService = authService;
            _patientService = patientService;
        }

        public IActionResult PatientRequest()
        {
            return View("Pages/PatientRequest");
        }


        public IActionResult PatientForgotPassword()
        {
            return View("Pages/PatientForgotPassword");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PatientForgotPassword(PatientForgotPassword model)
        {
            if (ModelState.IsValid)
            {
                if (_authService.PatientForgotPassword(model))
                {
                    var user = _context.Aspnetusers.FirstOrDefault(rq => rq.Email == model.Email);
                    return RedirectToAction("ResetPassword", user);
                }
            }
            return View("Pages/PatientForgotPassword",model);
        }

        public IActionResult ResetPassword(PatientResetPassword model)
        {
            return View("Pages/ResetPassword", model);
        }

        [HttpPost, ActionName("ResetPassword")]
        [ValidateAntiForgeryToken]
        public IActionResult Resetpassword(PatientResetPassword patientResetPassword)
        {
            if (ModelState.IsValid)
            {
                _authService.PatientResetPassword(patientResetPassword);
                _notyf.Success("Password Reset Successfully", 3);
                return RedirectToAction("PatientLogin");
            }
            _notyf.Error("Please provide correct credentials",3);
            return View("Pages/ResetPassword");
        }

        public IActionResult SubmitInfoAboutMe()
        {
            return View("PopUpModals/SubmitInfoAboutMe");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SubmitInfoAboutMe(PatientSubmitRequest userDetails)
        {
            if (ModelState.IsValid)
            {
                _patientService.PatientRequest(userDetails);
            }
            return View("PopUpModals/SubmitInfoAboutMe");
        }

        public IActionResult SomeoneElseInfo()
        {
            return View("PopUpModals/SomeoneElseInfo");
        }

        public IActionResult Profile()
        {
            int? userId = HttpContext.Session.GetInt32("userId");
            User? user = _context.Users.FirstOrDefault(u => u.Userid == userId);

            if (user != null)
            {
                var patientDetails = _patientService.Profile((int)userId);
                return View("Dashboard/Profile", patientDetails);
            }
            return RedirectToAction("Error");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Profile(PatientProfile profile)
        {
            int? userId = HttpContext.Session.GetInt32("userId");

            if (ModelState.IsValid)
            {
                _patientService.ProfileUpdate(profile, (int)userId);
            }
            return View("Dashboard/Profile");
        }


        public IActionResult CreateNewAccount()
        {
            return View("Pages/CreateNewAccount");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateNewAccount(CreateNewAccount newAccount)
        {
            if (ModelState.IsValid)
            {
                _authService.CreateNewAccount(newAccount);
                _notyf.Success("Account Created Successfully", 3);
                return RedirectToAction("PatientLogin");
            }
            return View("Pages/CreateNewAccount");
        }


        public IActionResult Dashboard()
        {
            int? userId = HttpContext.Session.GetInt32("userId");

            if (userId == null)
            {
                return View("Error");
            }

            User? user = _context.Users.FirstOrDefault(u => u.Userid == userId);

            if (user != null)
            {
                var dashboardVM = _patientService.PatientDashboard((int)userId);
                return View("Dashboard/Dashboard", dashboardVM);
            }

            return View("Error");
        }


        //View Document Page
        public IActionResult ViewDocument(int requestId)
        {
            int? userid = HttpContext.Session.GetInt32("userId");
            var document=_patientService.ViewDocument(requestId,(int)userid);
            return View("Dashboard/ViewDocument",document);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ViewDocument(ViewDocument document)
        {
            if (document != null)
            {
                _patientService.ViewDocument(document);
            }
            return ViewDocument(document.RequestId);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult Logout()
        {
            Response.Cookies.Delete("hallodoc");
            return RedirectToAction("PatientLogin", "Home");
        }
    }
}

HalloDoc/HalloDocWeb/Views/Shared/AdminDashboardHeader.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<link rel="stylesheet" href="~/css/Admin/AdminDashboard.css" asp-append-version="true" />

<style>

    #provider-tab:hover {
        cursor: pointer;
    }

        #provider-tab:hover .dropdown-menu {
            display: block;
        }

    #access-tab:hover {
        cursor: pointer;
    }

        #access-tab:hover .dropdown-menu {
            display: block;
        }
</style>


<header>
    <div class="container-fluid d-flex align-items-center justify-content-between">
        <img src="../../images/logo.png" alt="logo_icon" id="logo-icon" />
        <div class="d-flex justify-content-evenly align-items-center">
            <p class="m-2">Welcome <strong> @ViewData["User Name"] </strong></p>
            <a class="btn btn-outline-info mx-2" asp-controller="Admin" asp-action="Logout">
                <span class="h6 p-0 m-0 text-center" style="color: #10bce9;">Logout</span>
            </a>
            <img src="../../images/darkmode.png" alt="" onclick="myFunction()" class="lightmode" id="togglebtn-icon" />
        </div>
    </div>
</header>
<hr class="m-0">

<ul class="nav nav-pills ps-4 shadow" id="myTab" role="tablist">
    <li class="nav-item admin-tab" role="presentation" id="dashboard-tab">
        <a class="nav-link px-0" asp-controller="Admin" asp-action="AdminDashboard">
            <span class="tabHeader py-2 px-3">Dashboard</span>
        </a>
    </li>
    <li class="nav-item admin-tab" role="presentation" id="provider-location-tab">
        <a class="nav-link px-0" asp-controller="Admin" asp-action="ProviderLocation">
            <span class="tabHeader py-2 px-3">Provider Location</span>
        </a>
    </li>
    <li class="nav-item admin-tab" role="presentation" id="profile-tab">
        <a class="nav-link px-0" asp-controller="Admin" asp-action="AdminProfile">
            <span class="tabHeader py-2 px-3">My Profile</span>
        </a>
    </li>
    <li class="nav-item admin-tab" role="presentation" id="provider-tab">

        <a class="nav-link text-black" id="dropdownMenuButton1" role="button" data-bs-toggle="dropdown">
            Providers
        </a>

        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li>
                <a class="dropdown-item" asp-controller="Admin" asp-action="ProviderMenu">Provider</a>
            </li>
            <li>
                <a class="dropdown-item" asp-controller="Admin" asp-action="Scheduling">Scheduling</a>
            </li>
            <li>
                <a class="dropdown-item" asp-controller="Admin" asp-action="Invoicing">Invoicing</a>
            </li>
        </ul>
    </li>
    <li class="nav-item admin-tab" role="presentation" id="partner-tab">
        <a class="nav-link px-0" asp-controller="Admin" asp-action="Partners">
            <span class="tabHeader py-2 px-3">Partners</span>
        </a>
    </li>
    <li class="nav-item admin-tab" role="presentation" id="access-tab">
        <a class="nav-link text-black" id="dropdownMenuButton1" role="button" data-bs-toggle="dropdown">
            Access
        </a>

        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li>
                <a class="dropdown-item" asp-controller="Admin" asp-action="AccountAccess">Account Access</a>
            </li>
            <li>
                <a class="dropdown-item" asp-controller="Admin" asp-action="UserAccess">User Access</a>
            </li>
            <li>
                <a class="dropdown-item" asp-controller="Admin" asp-action="CreateAdminAccount">Create Admin Account</a>
            </li>
        </ul>
    </li>
    <li class="nav-item admin-tab" role="presentation" id="record-tab">
        <a class="nav-link px-0" asp-controller="Admin" asp-action="Records">
            <span class="tabHeader py-2 px-3">Records</span>
        </a>
    </li>
</ul>

HalloDoc/HalloDocWeb/Views/Shared/PatientDashboardHeader.cshtml
<header class="shadow">
    <div class="container-fluid d-flex align-items-center justify-content-between">
        <img src="../../images/logo.png" alt="logo_icon" id="logo-icon" />
        <div class="d-flex justify-content-evenly align-items-center">
            <p class="m-2">Welcome <strong> @ViewData["User Name"] </strong></p>
            <a class="btn btn-outline-info mx-2" asp-controller="Patient" asp-action="Logout">
                <span class="h6 p-0 m-0 text-center" style="color: #10bce9;">Logout</span>
            </a>
            <img src="../../images/darkmode.png" alt="" onclick="myFunction()" class="lightmode" id="togglebtn-icon" />
        </div>
    </div>
</header>

<ul class="nav nav-tabs">
    <li class="nav-item">
        <a asp-controller="Patient" asp-action="Dashboard" class="nav-link active"> Dashboard </a>
    </li>
    <li class="nav-item">
        <a asp-controller="Patient" asp-action="Profile" class="nav-link"> Profile </a>
    </li>
</ul>

<script>

    $(document).ready(function () {
        $('.nav-link').on('click', function () {
            // Remove the active class from all nav links
            $('.nav-link').removeClass('active');

            // Add the active class to the clicked nav link
            $(this).addClass('active');
        });
    });
</script>
<script>
    myFunction = () => {
        var element = document.body;
        element.classList.toggle("dark-mode");
        var img = element.querySelector(".lightmode")
        img.src.includes("darkmode") ? img.src = "~/wwwroot/images/lightmode.png" : img.src = "~/wwwroot/images/darkmode.png";
    }
</script>

HalloDoc/HalloDocWeb/Views/Shared/_AdminDashboardLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/css/intlTelInput.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.0/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/header.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/patient/phone.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />

</head>
<body class="admin-dashboard">

    <partial name="AdminDashboardHeader"/>

    <main role="main">
        @RenderBody()
    </main>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/2.0.0/js/dataTables.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    @await Component.InvokeAsync("Notyf")
    @RenderSection("Scripts", required: false)
</body>
</html>

<script>
    myFunction = () => {
        var element = document.body;
        element.classList.toggle("dark-mode");
        var img = element.querySelector(".lightmode")
        img.src.includes("darkmode") ? img.src = "../../images/lightmode.png" : img.src = "../../images/darkmode.png";
    }
</script>

HalloDoc/HalloDocWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HalloDocWeb</title>

    @* International Phone Number JS Plugin *@
    <script src="https://cdn.jsdelivr.net/npm/intl-tel-input@19.2.16/build/js/intlTelInput.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/intl-tel-input@19.2.16/build/css/intlTelInput.css">


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="~/css/patient/phone.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://cdn.datatables.net/1.13.10/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.13.10/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.10/css/dataTables.bootstrap5.min.css"></script>

</head>
<body>

    @RenderBody()

   
    @await Component.InvokeAsync("Notyf")
    @RenderSection("Scripts", required: false)
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<script>
    $(window).on('load', function () {
        $('#warningModal').modal('show');
    });
</script>

HalloDoc/HalloDocWeb/Views/Shared/_PatientDashboardLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/css/intlTelInput.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.0/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/header.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/patient/phone.css" />
    <link rel="stylesheet" href="~/css/site.css" />


</head>
<body class="patient-dashboard">

    <partial name="PatientDashboardHeader" />

    <main role="main">
        @RenderBody()
    </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("Notyf")
    @RenderSection("Scripts", required: false)
</body>
</html>

HalloDoc/HalloDocWeb/Views/Shared/footer.cshtml
<link rel="stylesheet" href="~/css/footer.css" asp-append-version="true" />

<div class="row d-flex position-absolute w-100">
    <footer class="position-bottom bottom-0 py-3 " style="background-color: #282828; ">
        <div class=" justify-content-md-end justify-content-center d-flex ">
            <a class="text-decoration-none " href=" "><span class="text-white ">Terms of Conditions</span></a>
            <span class="px-2 " style="color: grey; ">|</span>
            <a class="text-decoration-none " href=" "><span class="text-white ">Privacy Policy</span></a>
        </div>
    </footer>
</div>

HalloDoc/HalloDocWeb/Views/Shared/header.cshtml
<link rel="stylesheet" href="~/css/header.css" asp-append-version="true" />


<header class="shadow">
    <div class="d-flex align-items-center justify-content-between">
        <img src="../../images/logo.png" alt="logo_icon" id="logo-icon">
        <img src="../../images/darkmode.png" alt="" onclick="myFunction()" class="lightmode" id="togglebtn-icon">
    </div>
</header>

HalloDoc/HalloDocWeb/Views/Shared/warningModal.cshtml
<link rel="stylesheet" href="~/css/warningModal.css" asp-append-version="true" />



<div class="modal fade" id="warningModal" tabindex="-1" data-backdrop="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body row">
                <div class="col-12 align-items-center justify-content-center d-flex">
                    <div class="warning-icon">
                        <img src="../../images/warning-icon.svg" alt="" id="warning-icon">
                    </div>
                </div>
                <div class="col-12 justify-content-center d-flex">Information</div><br>
                <div class="col-12">When submitting a request, you must provide the correct contact information about the patient or the responsible party. Failure to provide correct phone number and email will delay service or be declined.</div>
                <div class="col-12 justify-content-center d-flex">
                    <button type="button" class="btn btn-secondary closeBtn" data-dismiss="modal">OK</button>
                </div>
            </div>

        </div>
    </div>
</div>


@* <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script> *@
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<script>
    $(".closeBtn").click(function () {

        $("#warningModal").modal('hide');
    })
</script>